export const DAYS = [
  {
    id: 1,
    icon: "/svg/snowflake.svg",
    color: "#BF4D40",
    font: "#F4EAD1",
    value: "01",
    gift: "Una carta virtual",
    message:
      "Barbara, esta carta lleva un pedacito de mi corazón en cada palabra. ¡Espero que te saque muchas sonrisas! P.D.: Mi letra es fea por eso es virtual.",
    secondColor: "#F4EAD1",
    url: "https://drive.google.com/file/d/1K31NoXrZkr3FQMqwlIhgNYw0vH6AzsIM/view?usp=sharing"
  },
  {
    id: 2,
    icon: "/svg/reindeer.svg",
    color: "#B7DBC6",
    font: "#122721",
    value: "02",
    gift: "Un labial de colores",
    message:
      "Amor, este labial es tan mágico como tú. Cambia de color, pero siempre es hermoso, igual que tu sonrisa que ilumina mi día en todos sus tonos. ❤️",
    secondColor: "#BF4D40",
  },
  {
    id: 3,
    icon: "/svg/christmas-tree.svg",
    color: "#BF4D40",
    font: "#F4EAD1",
    value: "03",
    gift: "Una playlist hecha por mí",
    message:
      "No soy un experto en tu música favorita, pero quise sumergirme en tu mundo para crear algo especial. Esta playlist está hecha desde mi corazón, escogiendo canciones que, aunque no sean mi estilo, tienen un mensaje claro: te amo. Espero que disfrutes cada nota tanto como yo disfruto estar a tu lado. ❤️",
    secondColor: "#F4EAD1",
url: "https://open.spotify.com/playlist/3RTFdpnj0LD5DHG4V5fY28?si=wqRJtCttRc2OwQ6DHV3Fxw&pi=u-QgU_ORgJTnuG"
  },
  {
    id: 4,
    icon: "/svg/lights-christmas.svg",
    color: "#F4EAD1",
    font: "#122721",
    value: "04",
    gift: "Diadema para maquillar",
    message:
      "Mi vida, esta diadema es para que cada vez que te maquilles recuerdes lo hermosa que eres, con o sin maquillaje. Porque tu belleza siempre viene del corazón. ❤️",
    secondColor: "#B7DBC6",
  },
  {
    id: 5,
    icon: "/svg/snowman.svg",
    color: "#BF4D40",
    font: "#F4EAD1",
    value: "05",
    gift: "Vale Todo Contigo",
    message:
      "Este vale es tuyo para usarlo como quieras: una cita soñada, una aventura loca o simplemente una tarde de abrazos viendo películas. Tú decides, yo feliz de compartirlo contigo. ❤️",
    secondColor: "#F4EAD1",
  },
  {
    id: 6,
    icon: "/svg/present-christmas.svg",
    color: "#B7DBC6",
    font: "#122721",
    value: "06",
    gift: "Cepillito",
    message:
      "Amor, este cepillito en forma de hoja es como tú: delicado, único y siempre cuidando de todo con amor. Espero que te saque una sonrisa cada vez que lo uses. 🌿❤️",
    secondColor: "#BF4D40",
  },
  {
    id: 7,
    icon: "/svg/reindeer-face.svg",
    color: "#BF4D40",
    font: "#F4EAD1",
    value: "07",
    gift: "Sabores y primeros encuentros 🍷✨",
    message:
      "Hoy es un día especial, no solo porque vamos a cocinar juntos, sino porque es la primera vez que te unirás a mi mundo de verdad. Quiero que conozcas a mi familia, que descubras parte de lo que soy y que juntos creemos recuerdos que sepan a Navidad… y a nosotros. ❤️",
    secondColor: "#F4EAD1",
  },
  {
    id: 8,
    icon: "/svg/christmas-sock.svg",
    color: "#F4EAD1",
    font: "#122721",
    value: "08",
    gift: "Una bufanda bonita",
    message:
      "Esta bufanda está lista para abrigarte, pero nada abriga más que mis abrazos.",
    secondColor: "#B7DBC6",
  },
  {
    id: 9,
    icon: "/svg/outdoor-snowman.svg",
    color: "#BF4D40",
    font: "#F4EAD1",
    value: "09",
    gift: "Tratamiento para el cabello",
    message:
      "Princesa, este tratamiento es para cuidar tu cabello, tan hermoso como tú. Porque quiero que te sientas tan especial como realmente eres, cada día. 💖",
    secondColor: "#F4EAD1",
  },
  {
    id: 10,
    icon: "/svg/christmas-ornament.svg",
    color: "#B7DBC6",
    font: "#122721",
    value: "10",
    gift: "El abrazo que guarda todo mi amor",
    message:
      "Hoy mi regalo para ti es algo que no puedes envolver, pero que encierra todo lo que siento por ti: un abrazo. Largo, cálido y lleno de amor, para que sientas lo importante que eres para mí. Cada segundo de ese abrazo llevará un pedacito de mi corazón, porque contigo quiero abrazar la vida entera.",
    secondColor: "#BF4D40",
  },
  {
    id: 11,
    icon: "/svg/christmas-wreath-decoration.svg",
    color: "#BF4D40",
    font: "#F4EAD1",
    value: "11",
    gift: "Gloss roto",
    message:
      "Mi amor, aunque este gloss esté un poquito roto, sigue siendo brillante y especial, justo como tú. Porque incluso las pequeñas imperfecciones nos hacen únicos y hermosos. 💋✨",
    secondColor: "#F4EAD1",
  },
  {
    id: 12,
    icon: "/svg/christmas-ball.svg",
    color: "#F4EAD1",
    font: "#122721",
    value: "12",
    gift: "Un picnic sorpresa",
    message:
      "Una mantita, comida rica y tu compañía... el plan perfecto para un día perfecto.",
    secondColor: "#B7DBC6",
  },
  {
    id: 13,
    icon: "/svg/gift.svg",
    color: "#BF4D40",
    font: "#F4EAD1",
    value: "13",
    gift: "Colitas para el cabello",
    message:
      "Amor, estas colitas son para que hagas peinados divertidos y juguetones, como tú, que siempre sabes cómo sacarle una sonrisa a mi corazón. 😘🎀",
    secondColor: "#F4EAD1",
  },
  {
    id: 14,
    icon: "/svg/christmas-tree-baubles.svg",
    color: "#B7DBC6",
    font: "#122721",
    value: "14",
    gift: "Un dibujo hecho por mí",
    message:
      "No soy un Picasso, pero cada trazo lleva mucho cariño. ¡Espero te guste!",
    secondColor: "#BF4D40",
  },
  {
    id: 15,
    icon: "/svg/christmas-sugarcane.svg",
    color: "#BF4D40",
    font: "#F4EAD1",
    value: "15",
    gift: "Delineador de ojos",
    message: "Guapa, este delineador es para que sigas dejando tu mirada de infarto por donde pases. Pero ojo, ¡no me dejes a nadie más hipnotizado que a mí! 😉🖤",
    secondColor: "#F4EAD1",
  },
  {
    id: 16,
    icon: "/svg/christmas-clothing-garment.svg",
    color: "#F4EAD1",
    font: "#122721",
    value: "16",
    gift: "Un masaje hecho por mí",
    message:
      "Relájate, hoy yo me encargo de consentirte como te mereces. ¡Es tu día especial!",
    secondColor: "#B7DBC6",
  },
  {
    id: 17,
    icon: "/svg/christmas-tree-color.svg",
    color: "#BF4D40",
    font: "#F4EAD1",
    value: "17",
    gift: "Prensa de cabello",
    message:
      "Amor, esta prensa es para que tu cabello quede siempre tan perfecto como tú. ¡Espero que cada vez que la uses recuerdes lo increíble que eres! 😘💇‍♀️",
    secondColor: "#F4EAD1",
  },
  {
    id: 18,
    icon: "/svg/christmas-decoration-holiday-2.svg",
    color: "#B7DBC6",
    font: "#122721",
    value: "18",
    gift: "Una tarde de juegos de mesa",
    message:
      "Saca tu lado competitivo, porque hoy vamos a divertirnos con un buen juego.",
    secondColor: "#BF4D40",
  },
  {
    id: 19,
    icon: "/svg/christmas-girl-hat.svg",
    color: "#BF4D40",
    font: "#F4EAD1",
    value: "19",
    gift: "Un set de velas aromáticas",
    message:
      "Unas velas que iluminarán cualquier espacio, pero nunca tanto como tú iluminas mi vida.",
    secondColor: "#F4EAD1",
  },
  {
    id: 20,
    icon: "/svg/christmas-cookie-dessert-2.svg",
    color: "#F4EAD1",
    font: "#122721",
    value: "20",
    gift: "Hornear galletas juntos",
    message:
      "Vamos a ensuciarnos las manos, pero terminaremos con algo delicioso (¡y con muchas risas!).",
    secondColor: "#B7DBC6",
  },
  {
    id: 21,
    icon: "/svg/christmas-card-letter.svg",
    color: "#BF4D40",
    font: "#F4EAD1",
    value: "21",
    gift: "Un cojín personalizado",
    message: "Para que siempre tengas algo cómodo que te recuerde a mí.",
    secondColor: "#F4EAD1",
  },
  {
    id: 22,
    icon: "/svg/hat-xmas.svg",
    color: "#B7DBC6",
    font: "#122721",
    value: "22",
    gift: "Un día sin tareas, ¡yo las hago todas!",
    message:
      "Hoy tú descansas, yo me encargo de todo. ¡Solo quiero verte feliz!",
    secondColor: "#BF4D40",
  },
  {
    id: 23,
    icon: "/svg/christmas-tree-christmas.svg",
    color: "#BF4D40",
    font: "#F4EAD1",
    value: "23",
    gift: "Un peluche",
    message:
      "Para que tengas un compañero de abrazos siempre que no esté cerca.",
    secondColor: "#F4EAD1",
  },
  {
    id: 24,
    icon: "/images/christmas.png",
    color: "#F4EAD1",
    font: "#122721",
    value: "24",
    gift: "Una cena especial hecha por mí",
    message:
      "Vamos a disfrutar de una cena deliciosa, preparada con todo mi amor.",
    secondColor: "#B7DBC6",
  },
];
